package payroll;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.FileOutputStream;
import java.sql.*;
import java.awt.Desktop;
import java.io.File;


public class PayslipPDFExporter {



    public static void exportPDF(int empId) {

        
        try {
            Connection con = DBConnection.getConnection();

            String sql = """
                SELECT e.name, e.department,
                       p.gross_salary, p.deductions, p.net_salary, p.pay_date
                FROM employees e
                JOIN payroll p ON e.id=p.emp_id
                WHERE e.id=?
            """;

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, empId);
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) return;

            Document doc = new Document();
            PdfWriter.getInstance(doc,
                    new FileOutputStream("Payslip_" + empId + ".pdf"));

            doc.open();

            // Fonts
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Font labelFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            Font valueFont = new Font(Font.FontFamily.HELVETICA, 12);

            // Title
            Paragraph title = new Paragraph("EMPLOYEE PAYSLIP", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph("------------------------------------------"));
            doc.add(new Paragraph(" "));

            // Data
            doc.add(new Paragraph("Name : " + rs.getString("name"), valueFont));
            doc.add(new Paragraph("Department : " + rs.getString("department"), valueFont));
            doc.add(new Paragraph(" "));

            doc.add(new Paragraph("Gross Salary : " + rs.getDouble("gross_salary"), valueFont));
            doc.add(new Paragraph("Deductions : " + rs.getDouble("deductions"), valueFont));
            doc.add(new Paragraph("Net Salary : " + rs.getDouble("net_salary"), valueFont));
            doc.add(new Paragraph("Pay Date : " + rs.getDate("pay_date"), valueFont));

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph("------------------------------------------"));
            doc.add(new Paragraph("Generated by Payroll System"));

            doc.close();

            
            File pdfFile = new File("Payslip_" + empId + ".pdf");

                if (Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(pdfFile);
                }


        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }
    
}
